# Generated by Django 5.1.7 on 2025-04-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
        ('recipes', '0008_userrecipecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpantry',
            name='related_ingredients',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='recipes.ingredient'),
        ),
    ]
