# Generated by Django 5.1.7 on 2025-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_cook_time_alter_recipe_prep_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('accessible', 'Accessible'), ('inaccessible', 'Inaccessible')], default='pending', max_length=20),
        ),
    ]
